-- MySQL Script generated by MySQL Workbench
-- Sun Aug 04 01:05:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema takenote
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `note` ;

CREATE TABLE IF NOT EXISTS `note` (
                                         `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                                         `title` VARCHAR(255) NULL,
                                         `description` VARCHAR(2000) NULL,
                                         `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         `created_by` INT(10) UNSIGNED NOT NULL,
                                         `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
                                         `updated_by` INT(10) UNSIGNED NULL DEFAULT NULL,
                                         `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
                                         `deleted_at` DATETIME NULL DEFAULT NULL,
                                         `deleted_by` INT(10) UNSIGNED NULL DEFAULT NULL,
                                         PRIMARY KEY (`id`),
                                         INDEX `fk_note_user1_idx` (`created_by` ASC),
                                         INDEX `fk_note_user2_idx` (`updated_by` ASC),
                                         INDEX `fk_note_user3_idx` (`deleted_by` ASC),
                                         CONSTRAINT `fk_note_user1`
                                             FOREIGN KEY (`created_by`)
                                                 REFERENCES `user` (`id`)
                                                 ON DELETE NO ACTION
                                                 ON UPDATE NO ACTION,
                                         CONSTRAINT `fk_note_user2`
                                             FOREIGN KEY (`updated_by`)
                                                 REFERENCES `user` (`id`)
                                                 ON DELETE NO ACTION
                                                 ON UPDATE NO ACTION,
                                         CONSTRAINT `fk_note_user3`
                                             FOREIGN KEY (`deleted_by`)
                                                 REFERENCES `user` (`id`)
                                                 ON DELETE NO ACTION
                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    COMMENT = 'Contains user created notes and their attributes.';

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
                                      `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                                      `name` VARCHAR(255) NOT NULL,
                                      `password` VARCHAR(255) NOT NULL,
                                      `email` VARCHAR(255) NOT NULL,
                                      `status` ENUM('LOCKED', 'CREATED', 'PENDING', 'ACTIVE', 'DISABLED') NOT NULL,
                                      `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      `created_by` INT(10) UNSIGNED NOT NULL,
                                      `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
                                      `updated_by` INT(10) UNSIGNED NULL DEFAULT NULL,
                                      `is_deleted` TINYINT(4) NOT NULL DEFAULT '0',
                                      `deleted_at` DATETIME NULL DEFAULT NULL,
                                      `deleted_by` INT(10) UNSIGNED NULL DEFAULT NULL,
                                      PRIMARY KEY (`id`),
                                      UNIQUE INDEX `email_UNIQUE` (`email` ASC),
                                      INDEX `fk_user_user1_idx` (`created_by` ASC),
                                      INDEX `fk_user_user2_idx` (`updated_by` ASC),
                                      INDEX `fk_user_user3_idx` (`deleted_by` ASC),
                                      CONSTRAINT `fk_user_user1`
                                          FOREIGN KEY (`created_by`)
                                              REFERENCES `user` (`id`)
                                              ON DELETE NO ACTION
                                              ON UPDATE NO ACTION,
                                      CONSTRAINT `fk_user_user2`
                                          FOREIGN KEY (`updated_by`)
                                              REFERENCES `user` (`id`)
                                              ON DELETE NO ACTION
                                              ON UPDATE NO ACTION,
                                      CONSTRAINT `fk_user_user3`
                                          FOREIGN KEY (`deleted_by`)
                                              REFERENCES `user` (`id`)
                                              ON DELETE NO ACTION
                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    COMMENT = 'Consolidates attributes that are common across all users in the system.';

-- -----------------------------------------------------
-- Table `user_login_attempt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_login_attempt` ;

CREATE TABLE IF NOT EXISTS `user_login_attempt` (
                                                    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
                                                    `email` VARCHAR(255) NOT NULL,
                                                    `origin_ip` VARCHAR(30) NOT NULL,
                                                    `success` TINYINT(4) NOT NULL,
                                                    `login_attempt_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
                                                    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8
    COMMENT = 'Records the login attempts for audit purposes.';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
