version: '3'

services:
  port-dev:
    build:
      context: ..
      dockerfile: ./docker/port/Dockerfile
    ports:
      - "15000:15000"
      - "8098:8098"
    environment: # Variables with REQUIRED defaults will need to pull from your own environment variables when the container is started
      - FLYWAY_URL=jdbc:mysql://database:3306/?useSSL=false
      - DB_URL=jdbc:mysql://database:3306/takenote?useSSL=false
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
